services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: loan-app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - loan-network
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: loan-nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        networks:
            - loan-network
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: loan-db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-loan}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-password}
            MYSQL_USER: ${DB_USERNAME:-loan_user}
        volumes:
            - dbdata:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - loan-network
networks:
    loan-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
